ci: update zunit bootstrap

diff --git a/tests/_support/bootstrap b/tests/_support/bootstrap
--- a/tests/_support/bootstrap
+++ b/tests/_support/bootstrap
@@ -1,5 +1,5 @@
 #!/usr/bin/env zsh
-setopt NO_GLOBAL_RCS NO_GLOBAL_EXPORT NO_RCS
+setopt NO_GLOBAL_RCS NO_GLOBAL_EXPORT NO_RCS NO_ALIASES
 
 # Log functions [[[
 function error(){ print -P "%F{red}[ERROR]%f: ${1}" && return 1; }
@@ -19,24 +19,30 @@ if [[ ! -d ${TMP_ZUNIT} ]]; then
     exit 1
 fi
 
-typeset -gAH ZINIT;
-ZINIT[HOME_DIR]=${TMP_ZUNIT};
-ZINIT[BIN_DIR]=$ZINIT[HOME_DIR]/zinit.git;
-ZINIT[COMPLETIONS_DIR]=$ZINIT[HOME_DIR]/completions;
-ZINIT[PLUGINS_DIR]=$ZINIT[HOME_DIR]/plugins;
-ZINIT[SNIPPETS_DIR]=$ZINIT[HOME_DIR]/snippets;
-ZINIT[ZCOMPDUMP_PATH]=$ZINIT[HOME_DIR]/zcompdump;
-ZPFX=$ZINIT[HOME_DIR]/polaris;
+typeset -g zi_dir="${TMP_ZUNIT}"
+typeset -gxUA ZINIT
+# DEBUG           'true'
+ZINIT+=(
+  BIN_DIR         ${zi_dir}/zinit.git
+  COMPLETIONS_DIR ${zi_dir}/completions SNIPPETS_DIR ${zi_dir}/snippets
+  HOME_DIR        ${zi_dir}             PLUGINS_DIR  ${zi_dir}/plugins
+  ZCOMPDUMP_PATH  ${zi_dir}/zcompdump   ZPFX         ${zi_dir}/polaris
+  POLARIS         ${zi_dir}/polaris
+)
+# typeset -gxH ZPFX="$ZINIT[POLARIS]"
+# FORK            'vladdoster'        REPO           'zinit-t'
+# typeset -gxAUH ZINIT=(${(kv)CONFIG})
 
 command git diff > ${ZINIT[HOME_DIR]}/unstaged.diff
-info 'creating test env'
+# info 'creating test env'
 git clone \
+    --quiet \
     --depth=1 \
     --dissociate \
     --no-hardlinks \
     --reference "${GIT_REPO}" \
     file://${GIT_REPO:A} \
-    "${ZINIT[BIN_DIR]}"
+    "${ZINIT[BIN_DIR]}" >/dev/null
 if (( $? != 0 )); then
     error "Unable to copy ${GIT_REPO} to ${TMP_ZUNIT}" >&2
     exit 1
@@ -44,25 +50,39 @@ fi
 
 if [[ -s $ZINIT[HOME_DIR]/unstaged.diff ]]; then
     (
-        git -C $ZINIT[BIN_DIR] apply $ZINIT[HOME_DIR]/unstaged.diff && \
+        git --quiet -C $ZINIT[BIN_DIR] apply $ZINIT[HOME_DIR]/unstaged.diff && \
             chmod g-rwX "${ZINIT[HOME_DIR]}" && \
-            zcompile "${ZINIT[BIN_DIR]}/zinit.zsh"
-    )
+            zcompile "${ZINIT[BIN_DIR]}/zinit.zsh" >/dev/null
+    ) >/dev/null
 fi
 (( $? != 0 )) && { error "Unable to copy ${GIT_REPO} to ${TMP_ZUNIT}" >&2; exit 1 }
 
-source $ZINIT[BIN_DIR]/zinit.zsh
-(( $? != 0 )) && { error "Unable to copy ${GIT_REPO} to ${TMP_ZUNIT}" >&2; exit 1 }
+hash -f
+builtin hash -d zinit=$zi_dir
+builtin hash -d zpfx=$zi_dir/polaris
+source $zi_dir/zinit.git/zinit.zsh
+(( $? != 0 )) && { error "Unable to source zinit" >&2; exit 1 }
+hash -f
+builtin hash -d zinit=$zi_dir
+builtin hash -d zpfx=$zi_dir/polaris
+
 # ]]]
 # Install Annexes [[[
-info 'installing test dependencies'
-for annex (binary-symlink default-ice); do
-  if [[ ! -d ${GIT_REPO}/tests/_support/$annex ]]; then;
-    git clone https://github.com/zdharma-continuum/zinit-annex-$annex ${GIT_REPO:A}/tests/_support/$annex
-  fi
-  zinit light ${GIT_REPO:A}/tests/_support/$annex
-  info "loaded $annex dependencies"
-done
+# +zi-log '{m} installing test dependencies'
+{
+  zinit for \
+    depth'1' \
+  @zdharma-continuum/zinit-annex-linkman \
+    depth'1' \
+  @zdharma-continuum/zinit-annex-default-ice \
+    ver'feat/logging' \
+  @zdharma-continuum/zinit-annex-binary-symlink
+} >/dev/null
++zi-log "{m} loaded $annex dependencies"
 # ]]]
+
++zi-log '{nl}{bar}'
+zinit zstatus
++zi-log '{bar}{nl}'
 
 # vim:ft=zsh:sw=2:sts=2:et:foldmarker=[[[,]]]:foldmethod=marker
